export const sportsIdMap = [
  {id: 1, name: 'soccer'},
  {id: 2, name: 'tennis'},
  {id: 3, name: 'golf'},
  {id: 4, name: 'cricket'},
  {id: 5, name: 'rugby-union'},
  {id: 8, name: 'motor-sport'},
  {id: 7511, name: 'baseball'},
  {id: 7522, name: 'basketball'},
  {id: 6, name: 'boxing'},
  {id: 3503, name: 'darts'},
  {id: 2152880, name: 'gaelic-games'},
  {id: 26420387, name: 'mixed-martial-arts'},
  {id: 27589895, name: 'olympics'},
  {id: 1477, name: 'rugby-league'},
  {id: 6422, name: 'snooker'},
  {id: 4339, name: 'grey-hound-racing'},
  {id: 7, name: 'horse-racing'},
  {id: 6423, name: 'american-football'},
]
